hname: !unsafe "{{.Node.Hostname}}"
ldap_root: "{{ domain | regex_replace('\\.',',dc=') | regex_replace('^', 'dc=') }}"
ldap_base: "{{ ldap_root | regex_replace('^', 'ou=people,') }}"
grafana_external: 0
