---
- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: pydeps.yml
- include_tasks: swarm.yml
- include_tasks: cron.yml
