- name: Add Docker repository.
  tags: install
  shell: >
     yum-config-manager --add-repo "https://download.docker.com/linux/centos/docker-{{ edition }}.repo"

- name: Install Docker
  tags: install
  yum:
    name: "docker-{{ edition }}"
    state: latest

- name: Start docker
  systemd:
    name: docker
    enabled: yes
    state: restarted
    masked: no

