- name: Generate the stack configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'compose.yaml.j2',   dest: "/tmp/{{ stack }}-compose.yaml",   desc: 'Compose' }
  loop_control:
    label: "{{ item.desc }}"

- name: "Install {{ stack }}"
  docker_stack:
    state: present
    name: "{{ stack }}"
    compose:
      - "/tmp/{{ stack }}-compose.yaml"
